domain_path: C:\Users\USER\workspaceV2\RTOS_platform\export\RTOS_platform\sw\freertos_ps7_cortexa9_1
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_hello_world
template: freertos_hello_world
